# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: first
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "first"
