# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: deploy
on:
  push:
    branches:
      - push-to-branch
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm src/index.js
      - run: git add .
      - run: git commit .
      - run: git push
