# See http\gs://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: deploy
on:
  push:
    branches:
      - push-to-branch
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          node src/index.js
          git config user.name github-actions
          git config user.email ${{ secrets.EMAIL }}
          git add .
          git commit -m 'add txt'
          git push origin action-create-txt
