# See https://zellwk.com/blog/github-actions-deploy/ an explanation of this code
name: ssh-action
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          known_hosts: "random"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: rsync test file
        run: rsync ${{ secrets.REMOTE_SSH_USER }}@${{ secrets.REMOTE_SSH_HOST }}:/home/test.txt ./
      - name: print test file
        run: cat ./test.txt
